#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players operation # aj.id = @s aj.id
execute as @e[type=#finalboss_ani:bone_entities,tag=aj.finalboss_ani,distance=..6.313] if score @s aj.id = # aj.id run kill @s
kill @s
scoreboard players set #execute aj.i 1