#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function finalboss_ani:animations/animation.finalboss2.ray/tree/bone_root_0-7
execute if score .this aj.frame matches 8..15 run function finalboss_ani:animations/animation.finalboss2.ray/tree/bone_root_8-15
execute if score .this aj.frame matches 16..23 run function finalboss_ani:animations/animation.finalboss2.ray/tree/bone_root_16-23
execute if score .this aj.frame matches 24..31 run function finalboss_ani:animations/animation.finalboss2.ray/tree/bone_root_24-31
execute if score .this aj.frame matches 32..39 run function finalboss_ani:animations/animation.finalboss2.ray/tree/bone_root_32-39
execute if score .this aj.frame matches 40..47 run function finalboss_ani:animations/animation.finalboss2.ray/tree/bone_root_40-47
execute if score .this aj.frame matches 48..50 run function finalboss_ani:animations/animation.finalboss2.ray/tree/bone_root_48-50