#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [2.7806f,-0.0281f,97.8453f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [0.2594f,0.189f,70.0708f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [0.2741f,0.2098f,67.9215f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [0.2846f,0.2222f,67.8511f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [0.2908f,0.2275f,69.127f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [0.2928f,0.2268f,71.017f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [0.2907f,0.2214f,72.7887f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [0.2845f,0.2127f,73.7097f]