#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-42.5f,0f,120f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-45.1557f,0.0136f,119.6878f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-42.5f,0f,120f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-29.9202f,-0.0796f,123.5143f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-12.6192f,-0.1834f,127.5837f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-0.0095f,-0.2178f,124.9953f]