#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-29.9074f,0f,84.4444f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-33.8672f,0f,95.625f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-37.3843f,0f,105.5556f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-40.3111f,0f,113.8194f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-42.5f,0f,120f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-44.7303f,0f,126.2974f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-45.5977f,0f,128.7464f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-45.4738f,0f,128.3965f]