#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [0.2742f,0.2018f,73.0476f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [0.26f,0.19f,70.07f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [0.2382f,0.1741f,64.1852f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [0.2072f,0.1515f,55.837f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [0.1702f,0.1244f,45.8465f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [0.13f,0.0951f,35.0349f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [0.0899f,0.0657f,24.2234f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [0.0528f,0.0386f,14.2329f]