#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-2.1889f,0f,6.1806f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-5.1157f,0f,14.4444f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-8.6328f,0f,24.375f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-12.5926f,0f,35.5556f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-16.8475f,0f,47.5694f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-21.25f,0f,60f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-25.6525f,0f,72.4306f]