#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [0.0218f,0.016f,5.8848f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [0f,0f,0f]