#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-44.7303f,0f,126.2974f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-43.7391f,0f,123.4985f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-42.8717f,0f,121.0496f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-42.5f,0f,120f]