#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,-47.5f,0f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [0f,-47.5f,0f]