#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0 ^-1.25 ^0 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0 ^-1.25 ^0 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0 ^-1.25 ^0 ~ ~