#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0 ^-1.875 ^0 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0 ^-1.875 ^0 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0 ^-1.875 ^0 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0 ^-1.875 ^0 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0 ^-1.875 ^0 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0 ^-1.875 ^0 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0 ^-1.875 ^0 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0 ^-1.875 ^0 ~ ~