#Project generated by Animated Java (https://animated-java.dev/)

tag @s remove aj.finalboss_ani.anim.animation.finalboss2.ray
tag @s remove aj.finalboss_ani.anim.animation.finalboss2.up
tag @s remove aj.finalboss_ani.anim.animation.finalboss2.down
tag @s remove aj.finalboss_ani.anim.animation.finalboss2.handup
tag @s remove aj.finalboss_ani.anim.animation.finalboss2.handdown
scoreboard players set @s aj.frame 0
scoreboard players operation .this aj.id = @s aj.id
execute as @e[type=minecraft:area_effect_cloud,tag=aj.finalboss_ani.bone,distance=..6.313] if score @s aj.id = .this aj.id run function finalboss_ani:zzz/execute/8
execute as @e[type=minecraft:armor_stand,tag=aj.finalboss_ani.bone,distance=..6.313] if score @s aj.id = .this aj.id run function finalboss_ani:zzz/execute/9
scoreboard players set #execute aj.i 1