#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.finalboss_ani.animation.finalboss2.handdown.loopMode matches 0 run function finalboss_ani:animations/animation.finalboss2.handdown/stop
execute if score @s aj.finalboss_ani.animation.finalboss2.handdown.loopMode matches 1 run function finalboss_ani:animations/animation.finalboss2.handdown/pause
execute if score @s aj.finalboss_ani.animation.finalboss2.handdown.loopMode matches 2 run function finalboss_ani:animations/animation.finalboss2.handdown/zzz/execute/32