#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..15 run function finalboss_ani:animations/animation.finalboss2.handdown/tree/level2_display_0-15