#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [14.8693f,12.9525f,136.6325f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [11.1452f,10.9697f,128.8169f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [5.5769f,8.0443f,117.9532f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-0.8115f,4.6699f,105.1112f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-6.9964f,1.3401f,91.3606f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-11.9538f,-1.4515f,77.7714f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-14.6599f,-3.2113f,65.4132f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-14.8903f,-3.6874f,57.5313f]