#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-14.0908f,-3.7383f,49.2305f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-12.5036f,-3.4571f,40.756f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-10.3708f,-2.9367f,32.3532f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-7.9347f,-2.2701f,24.2675f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-5.4373f,-1.5502f,16.7439f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-3.121f,-0.8699f,10.028f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-1.2278f,-0.3222f,4.3649f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [0f,0f,0f]