#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.finalboss_ani.bone.bone] run function finalboss_ani:animations/animation.finalboss2.handdown/tree/bone_root_top
execute if entity @s[tag=aj.finalboss_ani.bone.lefthand] run function finalboss_ani:animations/animation.finalboss2.handdown/tree/lefthand_root_top
execute if entity @s[tag=aj.finalboss_ani.bone.righthand] run function finalboss_ani:animations/animation.finalboss2.handdown/tree/righthand_root_top
execute if entity @s[tag=aj.finalboss_ani.bone.qwq] run function finalboss_ani:animations/animation.finalboss2.handdown/tree/qwq_root_top
execute if entity @s[tag=aj.finalboss_ani.bone.qwq2] run function finalboss_ani:animations/animation.finalboss2.handdown/tree/qwq2_root_top
execute if entity @s[tag=aj.finalboss_ani.bone.particle] run function finalboss_ani:animations/animation.finalboss2.handdown/tree/particle_root_top
execute if entity @s[tag=aj.finalboss_ani.bone.level1] run function finalboss_ani:animations/animation.finalboss2.handdown/tree/level1_root_top
execute if entity @s[tag=aj.finalboss_ani.bone.level2] run function finalboss_ani:animations/animation.finalboss2.handdown/tree/level2_root_top
execute store result entity @s Air short 1 run scoreboard players get .this aj.frame