#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if score @s aj.frame matches ..1 run function finalboss_ani:animations/animation.finalboss2.down/zzz/conditional/38
execute if score #execute aj.i matches 0 run function finalboss_ani:animations/animation.finalboss2.down/zzz/conditional/39