#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.finalboss_ani.animation.finalboss2.shield_rotate.loopMode matches 0 run function finalboss_ani:animations/animation.finalboss2.shield_rotate/stop
execute if score @s aj.finalboss_ani.animation.finalboss2.shield_rotate.loopMode matches 1 run function finalboss_ani:animations/animation.finalboss2.shield_rotate/pause
execute if score @s aj.finalboss_ani.animation.finalboss2.shield_rotate.loopMode matches 2 run function finalboss_ani:animations/animation.finalboss2.shield_rotate/zzz/execute/40