#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set # aj.i 1
execute at @s as @e[type=#finalboss_ani:bone_entities,tag=aj.finalboss_ani.bone] if score @s aj.id = .this aj.id run function finalboss_ani:zzz/execute/17