#Project generated by Animated Java (https://animated-java.dev/)

execute at @s as @e[type=minecraft:area_effect_cloud,tag=aj.finalboss_ani.bone] if score @s aj.id = .this aj.id run tp @s ~ ~ ~
function finalboss_ani:reset