#Project generated by Animated Java (https://animated-java.dev/)

tp @s[tag=aj.finalboss_ani.bone.bone] ^0 ^-1.625 ^0
tp @s[tag=aj.finalboss_ani.bone.particle] ^0 ^-1.625 ^0
tp @s[tag=aj.finalboss_ani.bone.qwq] ^0 ^-1.625 ^0
tp @s[tag=aj.finalboss_ani.bone.qwq2] ^0 ^-1.688 ^0
tp @s[tag=aj.finalboss_ani.bone.lefthand] ^0 ^-0.625 ^0.375
tp @s[tag=aj.finalboss_ani.bone.righthand] ^0 ^-0.625 ^-0.375
tp @s[tag=aj.finalboss_ani.bone.level2] ^0 ^-1.25 ^0
tp @s[tag=aj.finalboss_ani.bone.level1] ^0 ^-1.75 ^0
execute store result score .calc aj.i run data get entity @s Air
execute store result entity @s Air short 1 run scoreboard players add .calc aj.i 2