#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.finalboss_ani.bone.bone] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.finalboss_ani.bone.particle] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.finalboss_ani.bone.qwq] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.finalboss_ani.bone.qwq2] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.finalboss_ani.bone.lefthand] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.finalboss_ani.bone.righthand] Pose.Head set value [0f,0f,0f]
tp @s ~ ~ ~ ~ ~