#Project generated by Animated Java (https://animated-java.dev/)

tag @s remove aj.finalboss_ani.anim.animation.finalboss2.shield_rotate
scoreboard players set @s aj.frame 0
scoreboard players operation .oldValue aj.i = .noScripts aj.i
scoreboard players set .noScripts aj.i 1
function finalboss_ani:animations/animation.finalboss2.shield_rotate/next_frame
scoreboard players operation .noScripts aj.i = .oldValue aj.i
scoreboard players set @s aj.frame 0
scoreboard players set #execute aj.i 1