#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players operation .this aj.id = @s aj.id
execute as @e[type=minecraft:armor_stand,tag=aj.finalboss_ani.bone,distance=..6.498] if score @s aj.id = .this aj.id run function finalboss_ani:set_variant/zzz/execute/9
scoreboard players set #execute aj.i 1