#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.finalboss_ani.bone.bone] run function finalboss_ani:animations/animation.finalboss2.up/tree/bone_display_top
execute if entity @s[tag=aj.finalboss_ani.bone.lefthand] run function finalboss_ani:animations/animation.finalboss2.up/tree/lefthand_display_top
execute if entity @s[tag=aj.finalboss_ani.bone.righthand] run function finalboss_ani:animations/animation.finalboss2.up/tree/righthand_display_top
execute if entity @s[tag=aj.finalboss_ani.bone.qwq] run function finalboss_ani:animations/animation.finalboss2.up/tree/qwq_display_top
execute if entity @s[tag=aj.finalboss_ani.bone.qwq2] run function finalboss_ani:animations/animation.finalboss2.up/tree/qwq2_display_top
execute if entity @s[tag=aj.finalboss_ani.bone.particle] run function finalboss_ani:animations/animation.finalboss2.up/tree/particle_display_top
execute positioned as @s run tp @s ~ ~ ~ ~ ~