#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0 ^0.249 ^0.375 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0 ^0.377 ^0.375 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0 ^0.483 ^0.375 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0 ^0.562 ^0.375 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0 ^0.659 ^0.375 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0 ^0.648 ^0.375 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0 ^0.594 ^0.375 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0 ^0.562 ^0.375 ~ ~