#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0 ^-0.689 ^0 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0 ^-0.56 ^0 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0 ^-0.454 ^0 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0 ^-0.375 ^0 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0 ^-0.279 ^0 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0 ^-0.29 ^0 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0 ^-0.343 ^0 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0 ^-0.375 ^0 ~ ~