#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0 ^-0.814 ^0 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0 ^-0.685 ^0 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0 ^-0.579 ^0 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0 ^-0.5 ^0 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0 ^-0.404 ^0 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0 ^-0.415 ^0 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0 ^-0.468 ^0 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0 ^-0.5 ^0 ~ ~