#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^-1.688 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0 ^-1.609 ^0 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0 ^-1.503 ^0 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0 ^-1.375 ^0 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0 ^-1.231 ^0 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0 ^-1.078 ^0 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0 ^-0.922 ^0 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0 ^-0.77 ^0 ~ ~