#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0 ^-0.626 ^0 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0 ^-0.498 ^0 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0 ^-0.392 ^0 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0 ^-0.313 ^0 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0 ^-0.216 ^0 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0 ^-0.227 ^0 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0 ^-0.281 ^0 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0 ^-0.313 ^0 ~ ~