#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0 ^0.436 ^-0.375 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0 ^0.565 ^-0.375 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0 ^0.671 ^-0.375 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0 ^0.75 ^-0.375 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0 ^0.846 ^-0.375 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0 ^0.835 ^-0.375 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0 ^0.782 ^-0.375 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0 ^0.75 ^-0.375 ~ ~