#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^-0.813 ^-0.375 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0 ^-0.734 ^-0.375 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0 ^-0.628 ^-0.375 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0 ^-0.5 ^-0.375 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0 ^-0.356 ^-0.375 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0 ^-0.203 ^-0.375 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0 ^-0.047 ^-0.375 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0 ^0.105 ^-0.375 ~ ~