#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[type=minecraft:area_effect_cloud] run function finalboss_ani:animations/animation.finalboss2.up/tree/root_bone_name
execute if entity @s[type=minecraft:armor_stand] run function finalboss_ani:animations/animation.finalboss2.up/tree/display_bone_name