#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..63 run function finalboss_ani:animations/animation.finalboss2.shield_rotate/tree/lefthand_root_0-63
execute if score .this aj.frame matches 64..80 run function finalboss_ani:animations/animation.finalboss2.shield_rotate/tree/lefthand_root_64-80