#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..80 run function finalboss_ani:animations/animation.finalboss2.shield_rotate/tree/lefthand_display_0-80