#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [0f,72f,0f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [0f,67.5f,0f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [0f,63f,0f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [0f,58.5f,0f]
execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [0f,54f,0f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [0f,49.5f,0f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [0f,45f,0f]
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [0f,40.5f,0f]