#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [0f,-72f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [0f,-76.5f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [0f,-81f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [0f,-85.5f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [0f,-90f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-180f,-85.5f,180f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-180f,-81f,180f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-180f,-76.5f,180f]