#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [0f,24.5f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [0f,29f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [0f,33.5f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [0f,38f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [0f,42.5f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [0f,47f,0f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [0f,51.5f,0f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [0f,56f,0f]