#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [0f,-4.5f,0f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [0f,-9f,0f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [0f,-13.5f,0f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [0f,-18f,0f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [0f,-22.5f,0f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [0f,-27f,0f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [0f,-31.5f,0f]