#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [0f,36f,0f]
execute if score .this aj.frame matches 73 run data modify entity @s Pose.Head set value [0f,31.5f,0f]
execute if score .this aj.frame matches 74 run data modify entity @s Pose.Head set value [0f,27f,0f]
execute if score .this aj.frame matches 75 run data modify entity @s Pose.Head set value [0f,22.5f,0f]
execute if score .this aj.frame matches 76 run data modify entity @s Pose.Head set value [0f,18f,0f]
execute if score .this aj.frame matches 77 run data modify entity @s Pose.Head set value [0f,13.5f,0f]
execute if score .this aj.frame matches 78 run data modify entity @s Pose.Head set value [0f,9f,0f]
execute if score .this aj.frame matches 79 run data modify entity @s Pose.Head set value [0f,4.5f,0f]