#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [0f,-83.5f,0f]
execute if score .this aj.frame matches 73 run data modify entity @s Pose.Head set value [0f,-79f,0f]
execute if score .this aj.frame matches 74 run data modify entity @s Pose.Head set value [0f,-74.5f,0f]
execute if score .this aj.frame matches 75 run data modify entity @s Pose.Head set value [0f,-70f,0f]
execute if score .this aj.frame matches 76 run data modify entity @s Pose.Head set value [0f,-65.5f,0f]
execute if score .this aj.frame matches 77 run data modify entity @s Pose.Head set value [0f,-61f,0f]
execute if score .this aj.frame matches 78 run data modify entity @s Pose.Head set value [0f,-56.5f,0f]
execute if score .this aj.frame matches 79 run data modify entity @s Pose.Head set value [0f,-52f,0f]