#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-180f,-72f,180f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-180f,-67.5f,180f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-180f,-63f,180f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-180f,-58.5f,180f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-180f,-54f,180f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-180f,-49.5f,180f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-180f,-45f,180f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-180f,-40.5f,180f]