#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [-180f,83.5f,180f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [-180f,79f,180f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [-180f,74.5f,180f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [-180f,70f,180f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [-180f,65.5f,180f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [-180f,61f,180f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [-180f,56.5f,180f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [-180f,52f,180f]