#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64..71 run function finalboss_ani:animations/animation.finalboss2.shield_rotate/tree/level1_root_64-71
execute if score .this aj.frame matches 72..79 run function finalboss_ani:animations/animation.finalboss2.shield_rotate/tree/level1_root_72-79
execute if score .this aj.frame matches 80 run tp @s ^0 ^-1.75 ^0 ~ ~