#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64..71 run function finalboss_ani:animations/animation.finalboss2.shield_rotate/tree/level1_display_64-71
execute if score .this aj.frame matches 72..79 run function finalboss_ani:animations/animation.finalboss2.shield_rotate/tree/level1_display_72-79
execute if score .this aj.frame matches 80 run data modify entity @s Pose.Head set value [0f,0f,0f]