#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [0f,60.5f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [0f,65f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [0f,69.5f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [0f,74f,0f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [0f,78.5f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [0f,83f,0f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [0f,87.5f,0f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-180f,88f,180f]