#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [-180f,47.5f,180f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [-180f,43f,180f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [-180f,38.5f,180f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [-180f,34f,180f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [-180f,29.5f,180f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [-180f,25f,180f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [-180f,20.5f,180f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [-180f,16f,180f]