#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [-180f,11.5f,180f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [-180f,7f,180f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [-180f,2.5f,180f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [-180f,-2f,180f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [-180f,-6.5f,180f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [-180f,-11f,180f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [-180f,-15.5f,180f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [-180f,-20f,180f]