#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [-180f,72f,180f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [-180f,76.5f,180f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [-180f,81f,180f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [-180f,85.5f,180f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [0f,90f,0f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [0f,85.5f,0f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [0f,81f,0f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [0f,76.5f,0f]