#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [-180f,36f,180f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [-180f,40.5f,180f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [-180f,45f,180f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [-180f,49.5f,180f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [-180f,54f,180f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [-180f,58.5f,180f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [-180f,63f,180f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [-180f,67.5f,180f]