#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [-180f,-60.5f,180f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [-180f,-65f,180f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [-180f,-69.5f,180f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [-180f,-74f,180f]
execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [-180f,-78.5f,180f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [-180f,-83f,180f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [-180f,-87.5f,180f]
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [0f,-88f,0f]