#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,-47.5f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [0f,-43f,0f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [0f,-38.5f,0f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [0f,-34f,0f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [0f,-29.5f,0f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [0f,-25f,0f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [0f,-20.5f,0f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [0f,-16f,0f]