#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [-180f,-36f,180f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [-180f,-31.5f,180f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [-180f,-27f,180f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [-180f,-22.5f,180f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [-180f,-18f,180f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [-180f,-13.5f,180f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [-180f,-9f,180f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [-180f,-4.5f,180f]