#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [-180f,0f,180f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [-180f,4.5f,180f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [-180f,9f,180f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [-180f,13.5f,180f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [-180f,18f,180f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [-180f,22.5f,180f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [-180f,27f,180f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [-180f,31.5f,180f]