#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [0f,-36f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [0f,-40.5f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [0f,-45f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [0f,-49.5f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [0f,-54f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [0f,-58.5f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [0f,-63f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [0f,-67.5f,0f]