#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [-180f,-24.5f,180f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [-180f,-29f,180f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [-180f,-33.5f,180f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [-180f,-38f,180f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [-180f,-42.5f,180f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [-180f,-47f,180f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [-180f,-51.5f,180f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [-180f,-56f,180f]