#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0 ^-0.625 ^-0.375 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0 ^-0.625 ^-0.375 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0 ^-0.625 ^-0.375 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0 ^-0.625 ^-0.375 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0 ^-0.625 ^-0.375 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0 ^-0.625 ^-0.375 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0 ^-0.625 ^-0.375 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0 ^-0.625 ^-0.375 ~ ~