#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.finalboss_ani.animation.finalboss2.down.loopMode matches 0 run function finalboss_ani:animations/animation.finalboss2.down/stop
execute if score @s aj.finalboss_ani.animation.finalboss2.down.loopMode matches 1 run function finalboss_ani:animations/animation.finalboss2.down/pause
execute if score @s aj.finalboss_ani.animation.finalboss2.down.loopMode matches 2 run function finalboss_ani:animations/animation.finalboss2.down/zzz/execute/30