#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.finalboss_ani.bone.bone] ArmorItems[-1].tag.CustomModelData set value 1
data modify entity @s[tag=aj.finalboss_ani.bone.lefthand] ArmorItems[-1].tag.CustomModelData set value 5
data modify entity @s[tag=aj.finalboss_ani.bone.righthand] ArmorItems[-1].tag.CustomModelData set value 6