#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.finalboss_ani.bone.bone] ArmorItems[-1].tag.CustomModelData set value 9
data modify entity @s[tag=aj.finalboss_ani.bone.lefthand] ArmorItems[-1].tag.CustomModelData set value 10
data modify entity @s[tag=aj.finalboss_ani.bone.righthand] ArmorItems[-1].tag.CustomModelData set value 11
data modify entity @s[tag=aj.finalboss_ani.bone.level2] ArmorItems[-1].tag.CustomModelData set value 12
data modify entity @s[tag=aj.finalboss_ani.bone.level1] ArmorItems[-1].tag.CustomModelData set value 13