#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players add .aj.animation aj.finalboss_ani.animating 0
scoreboard players add .aj.anim_loop aj.finalboss_ani.animating 0
scoreboard players add .noScripts aj.i 0