#Project generated by Animated Java (https://animated-java.dev/)

scoreboard objectives add aj.i dummy
scoreboard objectives add aj.id dummy
scoreboard objectives add aj.frame dummy
scoreboard objectives add aj.finalboss_ani.animating dummy
scoreboard objectives add aj.finalboss_ani.animation.finalboss2.ray.loopMode dummy
scoreboard objectives add aj.finalboss_ani.animation.finalboss2.up.loopMode dummy
scoreboard objectives add aj.finalboss_ani.animation.finalboss2.down.loopMode dummy
scoreboard objectives add aj.finalboss_ani.animation.finalboss2.handup.loopMode dummy
scoreboard objectives add aj.finalboss_ani.animation.finalboss2.handdown.loopMode dummy
function finalboss_ani:reset_animation_flags
scoreboard players set .aj.finalboss_ani.framerate aj.i 1