#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.finalboss_ani.root] at @s rotated ~ 0 run function finalboss_ani:zzz/conditional/8
execute if score #execute aj.i matches 0 run function finalboss_ani:zzz/conditional/9