#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set .aj.animation aj.finalboss_ani.animating 0
scoreboard players set .aj.anim_loop aj.finalboss_ani.animating 0
scoreboard players set .noScripts aj.i 0