#Project generated by Animated Java (https://animated-java.dev/)

scoreboard objectives remove aj.finalboss_ani.animating
scoreboard objectives remove aj.finalboss_ani.animation.finalboss2.ray.loopMode
scoreboard objectives remove aj.finalboss_ani.animation.finalboss2.up.loopMode
scoreboard objectives remove aj.finalboss_ani.animation.finalboss2.down.loopMode
scoreboard objectives remove aj.finalboss_ani.animation.finalboss2.handup.loopMode
scoreboard objectives remove aj.finalboss_ani.animation.finalboss2.handdown.loopMode
scoreboard objectives remove aj.i
scoreboard objectives remove aj.id
scoreboard objectives remove aj.frame