#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [14.8903f,3.6874f,57.5313f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [14.6599f,3.2113f,65.4132f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [11.1097f,0.9599f,80.425f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [4.6125f,-2.6351f,96.9014f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-3.0626f,-6.7208f,112.9939f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-10.1463f,-10.4443f,126.8538f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-14.8693f,-12.9525f,136.6325f]