#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [1.2278f,0.3222f,4.3649f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [3.121f,0.8699f,10.028f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [5.4374f,1.5502f,16.7439f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [7.9347f,2.2701f,24.2674f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [10.3708f,2.9367f,32.3532f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [12.5036f,3.4571f,40.756f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [14.0908f,3.7383f,49.2304f]