#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function finalboss_ani:animations/animation.finalboss2.handup/tree/righthand_display_0-7
execute if score .this aj.frame matches 8..14 run function finalboss_ani:animations/animation.finalboss2.handup/tree/righthand_display_8-14