#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..14 run function finalboss_ani:animations/animation.finalboss2.handup/tree/righthand_root_0-14