#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.finalboss_ani.animation.finalboss2.up.loopMode matches 0 run function finalboss_ani:animations/animation.finalboss2.up/stop
execute if score @s aj.finalboss_ani.animation.finalboss2.up.loopMode matches 1 run function finalboss_ani:animations/animation.finalboss2.up/pause
execute if score @s aj.finalboss_ani.animation.finalboss2.up.loopMode matches 2 run function finalboss_ani:animations/animation.finalboss2.up/zzz/execute/36