#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0 ^-0.937 ^0 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0 ^-1.066 ^0 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0 ^-1.172 ^0 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0 ^-1.25 ^0 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0 ^-1.347 ^0 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0 ^-1.336 ^0 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0 ^-1.283 ^0 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0 ^-1.25 ^0 ~ ~