#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..15 run function finalboss_ani:animations/animation.finalboss2.down/tree/level1_display_0-15