#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^0.125 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0 ^0.046 ^0 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0 ^-0.06 ^0 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0 ^-0.189 ^0 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0 ^-0.332 ^0 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0 ^-0.485 ^0 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0 ^-0.641 ^0 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0 ^-0.794 ^0 ~ ~