#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^-0.375 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0 ^-0.454 ^0 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0 ^-0.56 ^0 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0 ^-0.689 ^0 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0 ^-0.832 ^0 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0 ^-0.985 ^0 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0 ^-1.141 ^0 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0 ^-1.294 ^0 ~ ~