#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0 ^-1.375 ^0 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0 ^-1.503 ^0 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0 ^-1.609 ^0 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0 ^-1.688 ^0 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0 ^-1.785 ^0 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0 ^-1.774 ^0 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0 ^-1.72 ^0 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0 ^-1.688 ^0 ~ ~