#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^-0.5 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0 ^-0.579 ^0 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0 ^-0.685 ^0 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0 ^-0.814 ^0 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0 ^-0.957 ^0 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0 ^-1.11 ^0 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0 ^-1.266 ^0 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0 ^-1.419 ^0 ~ ~