#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^-0.25 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0 ^-0.329 ^0 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0 ^-0.435 ^0 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0 ^-0.564 ^0 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0 ^-0.707 ^0 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0 ^-0.86 ^0 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0 ^-1.016 ^0 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0 ^-1.169 ^0 ~ ~